name: 🚧 Project Item
description: Create an issue for a project.  (Project maintainers only)
title: "🚧"
body:
- type: checkboxes
  attributes:
    label: I have done the items below . . .
    description: Please make sure to do the items below.
    options:
    - label: I have updated the title without removing the 🚧 emoji.
      required: true

- type: textarea
  attributes:
    label: Description
    description: A description of the feature and/or change from the user's perspective.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: |
      The list of items that need to be completed to satisfy the definition of done.
    value: |
      **This issue is finished when:**
      - [ ] Unit tests added
      - [ ] All unit tests pass
  validations:
    required: true
    render: markdown

- type: checkboxes
  attributes:
    label: ToDo Items
    description: Complete the following items before requesting a PR review.
    options:
    - label: Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**).
    - label: Issue linked to the correct project.
    - label: Issue linked to the correct milestone.
    - label: Draft pull request created and linked to this issue.

- type: textarea
  attributes:
    label: Issue Dependencies
    placeholder: |
      No Issue Dependencies Added.
      Example:
        - #10 Create new class
        - #20 Add unit tests to service
        - #30 Cleanup code in UI
    description: |
      A list of issues that are dependencies of this issue and need to be finished first.
      Use the '#\<issue-number\>' syntax to link an issue.
  validations:
    required: false

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      No Related Work Items Added.
      Example:
        - #10 Create new class
        - #20 Add unit tests to service
        - #30 Cleanup code in UI
    description: |
      A list of issues related to this issue but are not a dependency.
      Use the '#\<issue-number\>' syntax to link an issue.
  validations:
    required: false

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](../../code_of_conduct.md).
    options:
      - label: I agree to follow this project's Code of Conduct.
        required: true
