trigger:
  branches:
    include:
    - develop # Development Environment
    - master # Production Environment
    - feature/en-2324-improve-build-pipeline


variables:
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'any'
- name: buildConfiguration
  ${{ if notIn(variables['Build.SourceBranchName'], 'develop', 'master')}}:
    value: 'Debug'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop')}}:
    value: 'Debug'
  ${{ if eq(variables['Build.SourceBranchName'], 'master')}}:
    value: 'Release'
- name: coverageReportDirName
  value: 'CoverageReport'
- name: projectName
  value: 'Raptor'
- name: kinsonDigitalNugetFeed
  value: '1020f331-f22a-4330-a69a-78abfe6f6372/4c644bf2-f1e8-4f28-a3df-3bc9d3283df9'    
- name: pool
  value: 'KinsonServer'




stages:
- stage: 'Build_Stage' #🟢
  displayName: 'Build Stage'
  pool: '$(pool)'
  jobs:
  - template: templates/build-job-template.yml
    parameters:
      projectName: $(projectName)
      buildPlatform: $(buildPlatform)
      buildConfiguration: $(buildConfiguration)
      vstsFeed: '$(kinsonDigitalNugetFeed)'




- stage: 'Testing_Stage' #🟢
  displayName: 'Testing'
  pool: '$(pool)'
  jobs:
  - template: templates/test-job-template.yml
    parameters:
      projectName: $(projectName)
      buildPlatform: $(buildPlatform)      
      buildConfiguration: $(buildConfiguration)
      vstsFeed: '$(kinsonDigitalNugetFeed)'




- stage: 'Publish_Artifacts_Stage' #🟢
  displayName: 'Publish Artifacts'
  pool: '$(pool)'
  jobs:
  - template: templates/publish-job-template.yml
    parameters:
      projectName: $(projectName)
      buildPlatform: $(buildPlatform)
      buildConfiguration: $(buildConfiguration)
      vstsFeed: '$(kinsonDigitalNugetFeed)'
