name: 🚀Preview Release


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:


jobs:
  preview_release:
    name: Preview Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Restore DotNet Tools
      run: dotnet tool restore

    - name: Run Preview Release
      run: dotnet cicd PreviewRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NugetOrgApiKey: ${{ secrets.NUGET_ORG_API_KEY }}
        TwitterConsumerApiKey: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        TwitterConsumerApiSecret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        TwitterAccessToken: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TwitterAccessTokenSecret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}


  public-code-coverage:
    runs-on: ubuntu-latest
    name: Publish Code Coverage Results
    steps:
    - uses: actions/checkout@v3

    # TODO: Need to get this working and injecting the version to be used as the name of the code coverage report
    #       Do this once preview.3 has been released for the VersionMiner action
    #       Also add this to the prod-release.yml file as well

    # - name: Mine Version
    #   id: mine-version
    #   uses: KinsonDigital/VersionMiner@v1.0.0-preview.2
    #   with:
    #     repo-owner: KinsonDigital
    #     repo-name: Velaptor
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     branch-name: "${{ github.ref }}"
    #     trim-start-from-branch: "refs/heads/"
    #     file-format: xml # Not case sensitive
    #     file-path: "${{ github.workspace }}/Velaptor/Velaptor.csproj"
    #     version-keys: Version

    - name: Execute Unit Tests
      run: dotnet test "${{ github.workspace }}/Testing/VelaptorTests/VelaptorTests.csproj" -c Debug --collect:"XPlat Code Coverage"

    - uses: codecov/codecov-action@v3
      name: Publish Code Coverage Results
      with:
        directory: "${{ github.workspace }}/Testing/VelaptorTests/TestResults/"
        name: "Preview Release"
        fail_ci_if_error: true
        verbose: true
