name: 🚀Production Release


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:


jobs:
  production_release:
    name: Production Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Restore DotNet Tools
      run: dotnet tool restore

    - name: Run Production Release
      run: dotnet cicd ProductionRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NugetOrgApiKey: ${{ secrets.NUGET_ORG_API_KEY }}
        TwitterConsumerApiKey: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        TwitterConsumerApiSecret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        TwitterAccessToken: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TwitterAccessTokenSecret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}


  public-code-coverage:
    runs-on: ubuntu-latest
    name: Publish Code Coverage Results
    steps:
    - uses: actions/checkout@v3

    - name: Execute Unit Tests
      run: dotnet test "${{ github.workspace }}/Testing/VelaptorTests/VelaptorTests.csproj" -c Release --collect:"XPlat Code Coverage"

    - uses: codecov/codecov-action@v3
      name: Publish Code Coverage Results
      with:
        directory: "${{ github.workspace }}/Testing/VelaptorTests/TestResults/"
        name: "Production Release"
        fail_ci_if_error: true
        verbose: true
